// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJO3O1um6cD42IBOmf_JEX66dekvC-iis',
    appId: '1:707447606414:android:4ae754897a34d5c7848ddf',
    messagingSenderId: '707447606414',
    projectId: 'nutriplan-47cc4',
    databaseURL: 'https://nutriplan-47cc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriplan-47cc4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlA_wvMDRq_94PVwFpa4yCf1kLdhNVT0',
    appId: '1:707447606414:web:3903e6ad3d86b768848ddf',
    messagingSenderId: '707447606414',
    projectId: 'nutriplan-47cc4',
    authDomain: 'nutriplan-47cc4.firebaseapp.com',
    databaseURL: 'https://nutriplan-47cc4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nutriplan-47cc4.firebasestorage.app',
    measurementId: 'G-8GFD0Z3N7S',
  );

}